name: 0gchaind tps test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Build Tool
      run: |
        make build
    - name: Build Chain
      run: |
        git clone https://github.com/0glabs/0g-chain.git
        cd 0g-chain
        sudo LINK_STATICALLY=true make build-release
    - uses: JarvusInnovations/background-action@v1
      name: Bootstrap System Under Test (SUT)
      with:
        run: |
          ./localtestnet.sh &
        
        wait-on: |
          http://localhost:8545

        wait-for: 5m

        working-directory: 0g-chain
        
    - name: Run Benchmark Test
      run: |
        cd ../evmchainbench
        ./bin/evmchainbench run
