name: Signal Node - Sei

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build Tool
      run: |
        make build
    - name: Build Chain
      run: |
        git clone -b v5.9.0-hotfix https://github.com/sei-protocol/sei-chain.git
        cd sei-chain
        make build
        cp ./build/seid .
        make build-docker-node &> build.log
        make run-local-node &> chain.log &
        sleep 120
        echo 'chain.log'
        tail chain.log
        container_id=$(docker ps -q | head -n 1)
        docker exec $container_id sh -c 'eval echo ~$USER'
        docker exec $container_id ls -la /root
        docker cp $container_id:/root/.sei .
        ./build/seid tx evm send 0x20f33CE90A13a4b5E7697E3544c3083B8F8A51D4 10000000000 --from node_admin --home .sei <<EOF
        12345678
        EOF
        exit
        sleep 10
        cd ../../evmchainbench
        ./bin/evmchainbench run --tx-count 20000
